name: GitHub-Profile-Summary-Cards
on:
  # Schedule to run once a day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:
  # Run on pushes to main or master
  push: 
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Use your secret named "SUMMARY_CARD_TOKEN" 
          # Ensure this token has 'repo' scope access
          GITHUB_TOKEN: ${{ secrets.PROFILE }}
